INSERT INTO KillTeams (Name) VALUES 
('Vespid Stingwings'),
('Nemesis Claw'),
('Wrecka Krew'),
('Imperial Navy Breachers'),
('Gellerpox Infected'),
('Inquisitorial Agents'),
('Kasrkin'),
('Elucidian Starstriders'),
('Hand of the Archon'),
('Tempestus Aquilons'),
('Phobos Strike Team'),
('Mandrakes'),
('Brood Brothers'),
('Blades of Khaine'),
('Exaction Squad'),
('Hearthkyn Salvagers'),
('Death Korps'),
('Herrekyn Yaegirs'),
('Chaos Cult'),
('Warp Coven'),
('Angels of Death'),
('Kommandos'),
('Plague Marines'),
('Novitiates'),
('Blooded'),
('Legionaries'),
('Sanctifiers'),
('Pathfinders'),
('Void-Dancer Troupe'),
('Farsalker Kinband'),
('Hunter Clade'),
('Scout Squad'),
('Corsair Voidscarred'),
('Ratlings'),
('Fellgor Ravagers'),
('Gore Mongers'),
('Wyrmblade'),
('Hierotek Circle');