-- Insert KillTeams with their FactionId assigned
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (1, 'Vespid Stingwings', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (2, 'Nemesis Claw', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (3, 'Wrecka Krew', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (4, 'Imperial Navy Breachers', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (5, 'Gellerpox Infected', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (6, 'Inquisitorial Agents', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (7, 'Kasrkin', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (8, 'Scout Squad', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (9, 'Hand of the Archon', 4);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (10, 'Tempestus Aquilons', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (11, 'Phobos Strike Team', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (12, 'Mandrakes', 4);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (13, 'Brood Brothers', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (14, 'Blades of Khaine', 4);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (15, 'Exaction Squad', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (16, 'Hearthkyn Salvagers', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (17, 'Death Korps', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (18, 'Herrekyn Yaegirs', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (19, 'Chaos Cult', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (20, 'Warp Coven', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (21, 'Angels of Death', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (22, 'Kommandos', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (23, 'Plague Marines', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (24, 'Novitiates', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (25, 'Blooded', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (26, 'Legionaries', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (27, 'Sanctifiers', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (28, 'Pathfinders', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (29, 'Void-Dancer Troupe', 4);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (30, 'Farsalker Kinband', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (31, 'Hunter Clade', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (32, 'Elucidian Starstriders', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (33, 'Corsair Voidscarred', 4);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (34, 'Ratlings', 1);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (35, 'Fellgor Ravagers', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (36, 'Gore Mongers', 2);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (37, 'Wyrmblade', 3);
INSERT INTO KillTeam (Id, Name, FactionId) VALUES (38, 'Hierotek Circle', 3);